databases:
  - name: sas1db
    plan: free
    databaseName: sas1
    user: sas1

services:
  - type: web
    plan: free
    name: Security Alert System
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sas1.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4